import { todayYmd } from '@/shared/lib/todayYmd';
import { deriveEmployeeLeaveSummary } from './leaveAdmin.query-logic';
import { computeLeaveYearRange, sortByStartDateDesc } from '../leave/leave.query-logic';
import type { LeaveRequest } from '../leave/leave.types';
import type { EmployeeLeaveDetail, LeaveAdminJobType } from './leaveAdmin.types';

// 오늘 기준 상대 날짜 — leave.mock-data.ts와 동일한 방식(하드코딩된 절대 날짜는 시간이
// 지나면 상태 분류가 어긋난다).
const isoDaysFromToday = (offset: number): string => {
    const d = new Date();
    d.setDate(d.getDate() + offset);
    const pad = (n: number): string => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

// 실제 조직 기준 부서/영업소 목록 (임원직·현장직 → 부서, 승무직·미화직·정비직·조리직 → 영업소,
// 관리직 → 둘 중 하나 소속). 필터 옵션도 이 두 목록을 그대로 사용한다.
export const DEPARTMENT_OPTIONS = [
    '총무부',
    '전산부',
    '인사노무부',
    '경리부',
    '운행본부',
    '교통안전부',
    '관리부',
    '재해예방부',
];

export const BRANCH_OPTIONS = [
    '본사영업소',
    '충훈부영업소',
    '평촌영업소',
    '창박골영업소',
    '월암영업소',
    '군포영업소',
    '부곡영업소',
];

interface EmployeeSeed {
    employeeId: number;
    empNo: string; // 사번
    name: string;
    affiliation: string; // 부서 또는 영업소 이름
    position: string;
    positionOrder: number; // 직급 순서 — 낮을수록 상위 직급
    positionJobType: LeaveAdminJobType;
    hireDate: string; // mock 입사일 — 실제 입사일 API 연동 시 이 필드만 교체하면 된다.
    requests: LeaveRequest[];
}

const EMPLOYEE_SEEDS: EmployeeSeed[] = [
    {
        employeeId: 1,
        empNo: 'M20001',
        name: '최윤호',
        affiliation: '관리부',
        position: '총괄대표',
        positionOrder: 1,
        positionJobType: '임원직',
        hireDate: '2012-04-01',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-70),
                endDate: isoDaysFromToday(-68),
                days: 3,
                reason: '휴양',
                appliedAt: isoDaysFromToday(-75),
            },
        ],
    },
    {
        employeeId: 2,
        empNo: 'M20002',
        name: '이현우',
        affiliation: '인사노무부',
        position: '본부장',
        positionOrder: 2,
        positionJobType: '관리직',
        hireDate: '2015-01-12',
        // 신청 건이 10개를 넘어갈 때 상세 모달의 이력 표가 제대로 스크롤되는지 확인하기 위한 mock.
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-170),
                endDate: isoDaysFromToday(-168),
                days: 3,
                reason: '가족들과 함께 여행을 다녀오려고 합니다. 오랜만에 다 같이 시간을 보낼 수 있을 것 같아 미리 일정을 잡아두었습니다.',
                appliedAt: isoDaysFromToday(-175),
            },
            {
                id: 2,
                kind: '오전반차',
                status: '승인',
                startDate: isoDaysFromToday(-150),
                endDate: isoDaysFromToday(-150),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(-151),
            },
            {
                id: 3,
                kind: '연차',
                status: '반려',
                startDate: isoDaysFromToday(-130),
                endDate: isoDaysFromToday(-128),
                days: 3,
                reason: '개인적인 사정으로 며칠 자리를 비워야 할 것 같습니다. 자세한 사유는 인사팀에 별도로 말씀드리겠습니다.',
                appliedAt: isoDaysFromToday(-135),
            },
            {
                id: 4,
                kind: '연차',
                status: '취소',
                startDate: isoDaysFromToday(-115),
                endDate: isoDaysFromToday(-114),
                days: 2,
                reason: '일정 변경',
                appliedAt: isoDaysFromToday(-118),
            },
            {
                id: 5,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-100),
                endDate: isoDaysFromToday(-99),
                days: 2,
                reason: '경조사',
                appliedAt: isoDaysFromToday(-103),
            },
            {
                id: 6,
                kind: '오후반차',
                status: '승인',
                startDate: isoDaysFromToday(-80),
                endDate: isoDaysFromToday(-80),
                days: 0.5,
                reason: '개인 용무',
                appliedAt: isoDaysFromToday(-82),
            },
            {
                id: 7,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-60),
                endDate: isoDaysFromToday(-58),
                days: 3,
                reason: '최근 업무가 많아 몸살 기운이 있어서 며칠 쉬면서 컨디션을 회복하려고 합니다.',
                appliedAt: isoDaysFromToday(-65),
            },
            {
                id: 8,
                kind: '연차',
                status: '반려',
                startDate: isoDaysFromToday(-45),
                endDate: isoDaysFromToday(-44),
                days: 2,
                reason: '개인 사정',
                appliedAt: isoDaysFromToday(-48),
            },
            {
                id: 9,
                kind: '오전반차',
                status: '승인',
                startDate: isoDaysFromToday(-25),
                endDate: isoDaysFromToday(-25),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(-27),
            },
            {
                id: 10,
                kind: '연차',
                status: '진행중',
                startDate: isoDaysFromToday(10),
                endDate: isoDaysFromToday(11),
                days: 2,
                reason: '가족 행사',
                appliedAt: isoDaysFromToday(1),
            },
            {
                id: 11,
                kind: '오후반차',
                status: '진행중',
                startDate: isoDaysFromToday(25),
                endDate: isoDaysFromToday(25),
                days: 0.5,
                reason: '개인 용무',
                appliedAt: isoDaysFromToday(5),
            },
            {
                id: 12,
                kind: '연차',
                status: '진행중',
                startDate: isoDaysFromToday(45),
                endDate: isoDaysFromToday(46),
                days: 2,
                reason: '여행',
                appliedAt: isoDaysFromToday(10),
            },
            // 아래 3건은 작년/재작년 데이터 — 상세 모달의 연도 이동(◀ ▶)이 실제로 지난 연도로
            // 넘어가는지 확인하기 위한 mock.
            {
                id: 13,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-450),
                endDate: isoDaysFromToday(-448),
                days: 3,
                reason: '오래전부터 계획했던 가족 여행이라 미리 신청드립니다. 업무 인수인계는 팀원들과 사전에 충분히 협의해두었으니 참고 부탁드립니다.',
                appliedAt: isoDaysFromToday(-455),
            },
            {
                id: 14,
                kind: '오전반차',
                status: '승인',
                startDate: isoDaysFromToday(-400),
                endDate: isoDaysFromToday(-400),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(-401),
            },
            {
                id: 15,
                kind: '연차',
                status: '반려',
                startDate: isoDaysFromToday(-700),
                endDate: isoDaysFromToday(-698),
                days: 3,
                reason: '가족 여행',
                appliedAt: isoDaysFromToday(-705),
            },
        ],
    },
    {
        employeeId: 3,
        empNo: 'M20003',
        name: '박서연',
        affiliation: '인사노무부',
        position: '팀장',
        positionOrder: 3,
        positionJobType: '관리직',
        hireDate: '2019-07-01',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-60),
                endDate: isoDaysFromToday(-58),
                days: 3,
                reason: '휴양',
                appliedAt: isoDaysFromToday(-65),
            },
        ],
    },
    {
        employeeId: 4,
        empNo: 'M20004',
        name: '오태양',
        affiliation: '운행본부',
        position: '팀장',
        positionOrder: 3,
        positionJobType: '관리직',
        hireDate: '2018-09-01',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-45),
                endDate: isoDaysFromToday(-43),
                days: 3,
                reason: '휴양',
                appliedAt: isoDaysFromToday(-50),
            },
            {
                id: 2,
                kind: '오전반차',
                status: '승인',
                startDate: isoDaysFromToday(-20),
                endDate: isoDaysFromToday(-20),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(-22),
            },
        ],
    },
    {
        employeeId: 5,
        empNo: 'M20005',
        name: '김도윤',
        affiliation: '총무부',
        position: '매니저',
        positionOrder: 4,
        positionJobType: '관리직',
        hireDate: '2020-03-16',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-30),
                endDate: isoDaysFromToday(-29),
                days: 2,
                reason: '가족 여행',
                appliedAt: isoDaysFromToday(-35),
            },
            {
                id: 2,
                kind: '오전반차',
                status: '진행중',
                startDate: isoDaysFromToday(3),
                endDate: isoDaysFromToday(3),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(0),
            },
        ],
    },
    {
        employeeId: 6,
        empNo: 'M20006',
        name: '정민아',
        affiliation: '경리부',
        position: '대리',
        positionOrder: 5,
        positionJobType: '관리직',
        hireDate: '2021-11-02',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '취소',
                startDate: isoDaysFromToday(-2),
                endDate: isoDaysFromToday(-1),
                days: 2,
                reason: '일정 변경',
                appliedAt: isoDaysFromToday(-6),
            },
            {
                id: 2,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-90),
                endDate: isoDaysFromToday(-87),
                days: 4,
                reason: '연말 휴가',
                appliedAt: isoDaysFromToday(-95),
            },
        ],
    },
    {
        employeeId: 7,
        empNo: 'M20007',
        name: '강하늘',
        affiliation: '본사영업소',
        position: '대리',
        positionOrder: 5,
        positionJobType: '관리직',
        hireDate: '2022-05-23',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-15),
                endDate: isoDaysFromToday(-13),
                days: 3,
                reason: '가족 여행',
                appliedAt: isoDaysFromToday(-20),
            },
            {
                id: 2,
                kind: '오전반차',
                status: '진행중',
                startDate: isoDaysFromToday(5),
                endDate: isoDaysFromToday(5),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(0),
            },
        ],
    },
    {
        employeeId: 8,
        empNo: 'M20008',
        name: '최지훈',
        affiliation: '전산부',
        position: '사원',
        positionOrder: 6,
        positionJobType: '관리직',
        hireDate: '2024-04-08',
        requests: [
            {
                id: 1,
                kind: '오후반차',
                status: '승인',
                startDate: isoDaysFromToday(-5),
                endDate: isoDaysFromToday(-5),
                days: 0.5,
                reason: '개인 용무',
                appliedAt: isoDaysFromToday(-7),
            },
        ],
    },
    {
        employeeId: 9,
        empNo: 'M20009',
        name: '한소희',
        affiliation: '교통안전부',
        position: '사원',
        positionOrder: 6,
        positionJobType: '관리직',
        hireDate: '2023-06-19',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '진행중',
                startDate: isoDaysFromToday(20),
                endDate: isoDaysFromToday(21),
                days: 2,
                reason: '개인 사정',
                appliedAt: isoDaysFromToday(2),
            },
        ],
    },
    {
        employeeId: 10,
        empNo: 'M20010',
        name: '신유진',
        affiliation: '월암영업소',
        position: '사원',
        positionOrder: 6,
        positionJobType: '관리직',
        hireDate: '2025-02-10',
        requests: [],
    },
    {
        employeeId: 11,
        empNo: 'M20011',
        name: '윤서준',
        affiliation: '재해예방부',
        position: '사원',
        positionOrder: 6,
        positionJobType: '현장직',
        hireDate: '2024-10-14',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '반려',
                startDate: isoDaysFromToday(-40),
                endDate: isoDaysFromToday(-38),
                days: 3,
                reason: '개인 사정',
                appliedAt: isoDaysFromToday(-44),
            },
        ],
    },
    {
        employeeId: 12,
        empNo: 'M20012',
        name: '김태식',
        affiliation: '본사영업소',
        position: '기사',
        positionOrder: 7,
        positionJobType: '승무직',
        hireDate: '2017-06-05',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '승인',
                startDate: isoDaysFromToday(-25),
                endDate: isoDaysFromToday(-24),
                days: 2,
                reason: '개인 사정',
                appliedAt: isoDaysFromToday(-30),
            },
        ],
    },
    {
        employeeId: 13,
        empNo: 'M20013',
        name: '이말순',
        affiliation: '월암영업소',
        position: '미화원',
        positionOrder: 7,
        positionJobType: '미화직',
        hireDate: '2016-09-19',
        requests: [
            {
                id: 1,
                kind: '오전반차',
                status: '승인',
                startDate: isoDaysFromToday(-8),
                endDate: isoDaysFromToday(-8),
                days: 0.5,
                reason: '병원 진료',
                appliedAt: isoDaysFromToday(-9),
            },
        ],
    },
    {
        employeeId: 14,
        empNo: 'M20014',
        name: '박정비',
        affiliation: '군포영업소',
        position: '정비기사',
        positionOrder: 7,
        positionJobType: '정비직',
        hireDate: '2019-02-14',
        requests: [
            {
                id: 1,
                kind: '연차',
                status: '진행중',
                startDate: isoDaysFromToday(15),
                endDate: isoDaysFromToday(16),
                days: 2,
                reason: '가족 여행',
                appliedAt: isoDaysFromToday(1),
            },
        ],
    },
    {
        employeeId: 15,
        empNo: 'M20015',
        name: '최조리',
        affiliation: '부곡영업소',
        position: '조리사',
        positionOrder: 7,
        positionJobType: '조리직',
        hireDate: '2020-11-30',
        requests: [],
    },
];

const today = todayYmd();

export const EMPLOYEE_LEAVE_RECORDS: EmployeeLeaveDetail[] = EMPLOYEE_SEEDS.map((seed) => ({
    ...deriveEmployeeLeaveSummary(
        {
            employeeId: seed.employeeId,
            empNo: seed.empNo,
            name: seed.name,
            affiliation: seed.affiliation,
            position: seed.position,
            positionOrder: seed.positionOrder,
            positionJobType: seed.positionJobType,
        },
        seed.requests,
        computeLeaveYearRange(seed.hireDate, today),
    ),
    requests: sortByStartDateDesc(seed.requests),
}));
